SELECT distinct
stc_person_id as "Studen ID"
,EXTRACT(YEAR FROM age('2026-10-17', birth_date))
FROM 
   STUDENT_ACAD_CRED SAC 
    INNER JOIN STC_STATUSES SS ON SAC.STUDENT_ACAD_CRED_ID = SS.STUDENT_ACAD_CRED_ID and POS=1
	LEFT OUTER JOIN GRADES ON STC_VERIFIED_GRADE = GRADES_ID 
	INNER JOIN PERSON ON STC_PERSON_ID =  PERSON.ID 
	WHERE 
 (STC_STATUS IN ('A','N') OR (STC_STATUS = 'D' AND GRD_GRADE = 'W'))
AND STC_TERM IN ( '2026SP','2025FA','2025SU')
and stc_person_id in  
(

)