
Select DISTINCT
TERM_REPORTING_YEAR::text
,STC_PERSON_ID
,STC_SUBJECT
,STC_CRED
,STC_COURSE_NAME
,LEFT(STC_SECTION_NO,2) 
,CASE LEFT(STC_SECTION_NO,2) 
	WHEN 'FB' THEN 'Flexible Blend'
	WHEN 'BL' THEN 'Blended'
	WHEN 'OP' THEN 'Online Proctored'
	WHEN 'FE' THEN 'Field Experience'
	WHEN 'HF' THEN 'HyFlex'
	ELSE
		CASE SEC_COURSE_TYPES
			WHEN '1' THEN 'Face To Face'
			WHEN '2' THEN 'Distance Learning'
			WHEN '5' THEN 'Online'
			WHEN '8' THEN 'Hybrid'
			WHEN '7' THEN 'Other'
			END
END as "Course Type"
--,SEC_COURSE_TYPES
,M.GRD_GRADE "MidTerm Grade"
,STC_STATUS
,F.GRD_GRADE "Final Grad"
,CASE F.GRD_GRADE
	WHEN 'A' THEN 1
	WHEN 'B' THEN 1
	WHEN 'C' THEN 1
	WHEN 'P' THEN 1
	WHEN 'S' THEN 1
	WHEN 'D' THEN 0
	WHEN 'F' THEN 0

	ELSE 0 -- W doesn't count towards success rate
	END as "Success"
,CASE F.GRD_GRADE
	WHEN 'A' THEN 1
	WHEN 'B' THEN 1
	WHEN 'C' THEN 1
	WHEN 'P' THEN 1
	WHEN 'D' THEN 1
	WHEN 'F' THEN 1
	WHEN 'S' THEN 1
	ELSE 0
	END as "Retention"
FROM STUDENT_ACAD_CRED SAC 
    INNER JOIN STC_STATUSES SS ON SAC.STUDENT_ACAD_CRED_ID = SS.STUDENT_ACAD_CRED_ID and POS=1
	LEFT OUTER JOIN GRADES F ON STC_VERIFIED_GRADE = F.GRADES_ID 
	INNER JOIN TERMS ON STC_TERM=TERMS_ID
	INNER JOIN STUDENT_COURSE_SEC ON STC_STUDENT_COURSE_SEC = STUDENT_COURSE_SEC_ID
		LEFT OUTER JOIN GRADES M ON SCS_MID_TERM_GRADE1 = M.GRADES_ID
	INNER JOIN dbo.COURSE_SECTIONS_LS ON SCS_COURSE_SECTION = COURSE_SECTIONS_ID
WHERE (STC_STATUS IN ('A','N') OR (STC_STATUS = 'D' AND F.GRD_GRADE = 'W'))
AND TERM_REPORTING_YEAR IN (2025)--(2024,2023, 2022, 2021, 2020, 2019)
AND STC_SECTION_NO NOT LIKE 'DC%'
AND SEC_COURSE_TYPES IN ('1','2','3','4','5','6','7','8')
AND STC_ACAD_LEVEL = 'UG'
--AND F.GRD_GRADE != 'W'
----AND STC_TERM !='2022FA'
