select distinct 
stc_person_id 
,case when stc_term in ('2026SP', '2025FA', '2025SU') then '26' else null end as "fiscal year"
,case when county = '001' then 'Adams' 
when county = '003' then 'Alexander'
when county = '005' then 'Bond'
when county = '007' then 'Boone'
when county = '009' then 'Brown'
when county = '011' then 'Bureau'
when county = '013' then 'Calhoun'
when county = '015' then 'Carroll'
when county = '017' then 'Cass'
when county = '019' then 'Champaign'
when county = '021' then 'Christian'
when county = '023' then 'Clark'
when county = '025' then 'Clay'
when county = '027' then 'Clinton'
when county = '029' then 'Coles'
when county = '031' then 'Cook'
when county = '033' then 'Crawford'
when county = '035' then 'Cumberland'
when county = '037' then 'De Kalb'
when county = '039' then 'De Witt'
when county = '041' then 'Douglas'
when county = '043' then 'Du Page'
when county = '045' then 'Edgar'
when county = '047' then 'Edwards'
when county = '049' then 'Effingham'
when county = '051' then 'Fayette'
when county = '053' then 'Ford'
when county = '055' then 'Franklin'
when county = '057' then 'Fulton'
when county = '059' then 'Gallatin'
when county = '061' then 'Greene'
when county = '063' then 'Grundy'
when county = '065' then 'Hamilton'
when county = '067' then 'Hancock'
when county = '069' then 'Hardin'
when county = '071' then 'Henderson'
when county = '073' then 'Henry'
when county = '075' then 'Iroquois'
when county = '077' then 'Jackson'
when county = '079' then 'Jasper'
when county = '081' then 'Jefferson'
when county = '083' then 'Jersey'
when county = '085' then 'Jo Daviess'
when county = '087' then 'Johnson'
when county = '089' then 'Kane'
when county = '091' then 'Kankakee'
when county = '093' then 'Kendall'
when county = '095' then 'Knox'
when county = '097' then 'Lake'
when county = '099' then 'La Salle'
when county = '101' then 'Lawerence'
when county = '103' then 'Lee'
when county = '105' then 'Livingston'
when county = '107' then 'Logan'
when county = '109' then 'McDonough'
when county = '111' then 'McHenry'
when county = '113' then 'McLean'
when county = '115' then 'Macon'
when county = '117' then 'Massac'
when county = '119' then 'Madison'
when county = '121' then 'Marion'
when county = '123' then 'Marshall'
when county = '125' then 'Mason'
when county = '127' then 'Massac'
when county = '129' then 'Menard'
when county = '131' then 'Mercer'
when county = '133' then 'Monroe'
when county = '135' then 'Montgomery'
when county = '137' then 'Morgan'
when county = '139' then 'Moultrie'
when county = '141' then 'Ogle'
when county = '143' then 'Peoria'
when county = '145' then 'Perry'
when county = '147' then 'Piatt'
when county = '149' then 'Pike'
when county = '151' then 'Pope'
when county = '153' then 'Pulaski'
when county = '155' then 'Putnam'
when county = '157' then 'Randolph'
when county = '159' then 'Richland'
when county = '161' then 'Rock Island'
when county = '163' then 'St. Clair'
when county = '165' then 'Saline'
when county = '167' then 'Sangamon'
when county = '169' then 'Schuyler'
when county = '171' then 'Scott'
when county = '173' then 'Shelby'
when county = '175' then 'Stark'
when county = '177' then 'Stephenson'
when county = '179' then 'Tazewell'
when county = '181' then 'Union'
when county = '183' then 'Vermilion'
when county = '185' then 'Wabash'
when county = '187' then 'Warren'
when county = '189' then 'Washington'
when county = '191' then 'Wayne'
when county = '193' then 'White'
when county = '195' then 'Whiteside'
when county = '197' then 'Will'
when county = '199' then 'Williamson'
when county = '201' then 'Winnebago'
when county = '203' then 'Woodford'
when county = '999' then 'Correctional, Out-of-state, or Foreign'
else null 
end as "County"

from student_acad_cred 
inner join stc_statuses on student_acad_cred.student_acad_cred_id = stc_statuses.student_acad_cred_id and pos = '1' 
left outer join grades gds on stc_verified_grade = gds.grades_id 
inner join person on stc_person_id = person.id 
left outer join address on person.preferred_address = address.address_id 
left outer join address_ls a1 on address.address_id = a1.address_id and a1.pos = '1' and a1.address_lines is not null 
left outer join address_ls a2 on address.address_id = a2.address_id and a2.pos = '2' and a2.address_lines is not null 
left outer join perphone p1 on person.id = p1.id and p1.pos = '1' 
left outer join perphone p2 on person.id = p2.id and p2.pos = '2'
left outer join people_email pe1 on person.id = pe1.id and pe1.person_email_types = 'KC' 
left outer join people_email pe2 on person.id =pe2.id and pe2.person_email_types = 'PE' 
left outer join counties on address.county = counties.counties_id 

where (stc_status in ('A', 'N') or (stc_status = 'D' and grd_grade like 'W%')) 
and stc_term in ('2026SP', '2025FA', '2025SU')
and stc_acad_level = 'UG'