Select distinct stc_person_id
,first_name
,last_name
,a1.address_lines
,a2.address_lines
,city
,state
,zip
,p1.personal_phone_number
,p2.personal_phone_number
,pe1.person_email_addresses
,pe2.person_email_addresses
FROM STUDENT_ACAD_CRED SAC 
    INNER JOIN STC_STATUSES SS ON SAC.STUDENT_ACAD_CRED_ID = SS.STUDENT_ACAD_CRED_ID and POS=1
	LEFT OUTER JOIN GRADES ON STC_VERIFIED_GRADE = GRADES_ID 
	INNER JOIN PERSON ON STC_PERSON_ID =  PERSON.ID 
	 LEFT OUTER JOIN ADDRESS ON PERSON.PREFERRED_ADDRESS = ADDRESS.ADDRESS_ID
     LEFT OUTER JOIN ADDRESS_LS a1 ON ADDRESS.ADDRESS_ID = A1.ADDRESS_ID AND A1.POS = 1 AND A1.ADDRESS_LINES IS NOT NULL
     LEFT OUTER JOIN ADDRESS_LS a2 ON ADDRESS.ADDRESS_ID = A2.ADDRESS_ID AND A2.POS = 2 AND A2.ADDRESS_LINES IS NOT NULL
     LEFT OUTER JOIN PERPHONE p1 ON PERSON.ID = P1.ID AND P1.POS = 1
     LEFT OUTER JOIN PERPHONE p2 ON PERSON.ID = P2.ID AND P2.POS = 2
     LEFT OUTER JOIN dbo.PEOPLE_EMAIL PE1 ON PERSON.ID = PE1.ID AND PE1.PERSON_EMAIL_TYPES = 'KC'
	 LEFT OUTER JOIN dbo.PEOPLE_EMAIL PE2 ON PERSON.ID = PE2.ID AND PE2.PERSON_EMAIL_TYPES = 'PE'
where (STC_STATUS IN ('A','N') OR (STC_STATUS = 'D' AND GRD_GRADE = 'W')) 
and stc_term in ('2026SP', '2025FA', '2025SU')